-- -- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/

-- -- Default beziers
-- hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
-- hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
-- hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
-- hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
-- hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })
-- hl.curve("overshoot",      { type = "bezier", points = { {0.5, 0.9}, {0.1, 1.1}     } })

-- -- Default springs
-- hl.curve("easy",           { type = "spring", mass = 1, stiffness = 500, dampening = 35 })
-- hl.curve("rubber",         { type = "spring", mass = 1, stiffness = 200,  dampening = 15 })

-- -- Animations
-- hl.animation({ leaf = "global",              enabled = true, speed = 3, bezier = "quick"                 })
-- hl.animation({ leaf = "windows",             enabled = true, speed = 3, spring = "easy",  style = "slide" })
-- hl.animation({ leaf = "workspaces",          enabled = true, speed = 5, bezier = "quick", style = "slide" })
-- hl.animation({ leaf = "specialWorkspaceIn",  enabled = true, speed = 2, bezier = "quick", style = "slide top"})
-- hl.animation({ leaf = "specialWorkspaceOut", enabled = true, speed = 2, bezier = "quick", style = "slide bottom"})


-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.curve("overshotW", { type = "bezier", points = { { 0.15, 0.85 }, { 0.1, 1.03 } } })
hl.curve("overshot", { type = "bezier", points = { { 0.15, 0.85 }, { 0.1, 1.1 } } })
hl.curve("smoothOut", { type = "bezier", points = { { 0.25, 1 }, { 0.5, 1 } } })
hl.curve("smoothIn", { type = "bezier", points = { { 0.25, 1 }, { 0.5, 1 } } })
hl.curve("softSnap", { type = "bezier", points = { { 0.4, 0 }, { 0.2, 1 } } })
hl.curve("fluent", { type = "bezier", points = { { 0.0, 0.0 }, { 0.2, 1.0 } } })
hl.curve("easeInOutExpo", { type = "bezier", points = { { 0.87, 0 }, { 0.13, 1 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 1,
    bezier = "overshot",
    style = "popin 80%",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 2.5,
    bezier = "softSnap",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 1.5,
    bezier = "softSnap",
})
hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 3,
    bezier = "overshotW",
})
hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 4,
    bezier = "smoothIn",
})
hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 5,
    bezier = "softSnap",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 2.5,
    bezier = "smoothIn",
})
hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 2.5,
    bezier = "smoothIn",
})
hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 2.5,
    bezier = "smoothOut",
})
hl.animation({
    leaf = "fadeSwitch",
    enabled = true,
    speed = 2.5,
    bezier = "smoothIn",
})
hl.animation({
    leaf = "fadeShadow",
    enabled = true,
    speed = 2.5,
    bezier = "smoothIn",
})
hl.animation({
    leaf = "fadeDim",
    enabled = true,
    speed = 2.5,
    bezier = "smoothIn",
})
hl.animation({
    leaf = "fadeDpms",
    enabled = true,
    speed = 2.5,
    bezier = "smoothIn",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 2.5,
    bezier = "softSnap",
    style = "slidefadevert",
})
hl.animation({
    leaf = "specialWorkspace",
    enabled = true,
    speed = 3.5,
    bezier = "overshot",
    style = "slidefadevert 30%",
})

hl.config({
    animations = {
        enabled = true,
        -- BEZIER CURVES
        -- We hebben de overshot-curve aangepast (laatste getal naar 1.15) voor een duidelijkere bounce.
        -- Ook is de start-versnelling wat feller gemaakt.
        -- WINDOW MOVEMENTS (Versneld van 5/4 naar 3 deciseconden)
        -- LAYERS (Versneld naar 4 en 5)
        -- FADE ANIMATIONS (Versneld van 4 naar 2.5)
        -- WORKSPACES (Versneld van 5 naar 3.5 voor een snappy gevoel met de nieuwe overshot)
    },
    dwindle = {
        preserve_split = true,
    },
})
